name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven (compile phase)
        run: |
          cd GestorTareas/GestorTareasBackend/gestortareasbackend/gestortareasbackend
          mvn compile

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests with Maven (verify phase)
        run: |
          cd GestorTareas/GestorTareasBackend/gestortareasbackend/gestortareasbackend
          mvn verify

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Print deployment message
        run: echo "Contrucción en progreso..."
