# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
    - task: Checkout@2
      displayName: 'Checkout code'

    - task: UseJava@1
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
        jdkVersionOption: '1.17'

    - script: |
        cd GestorTareas/GestorTareasBackend/gestortareasbackend/gestortareasbackend
        mvn compile
      displayName: 'Build with Maven (compile phase)'

- job: Test
  dependsOn: Build
  steps:
    - task: Checkout@2
      displayName: 'Checkout code'

    - task: UseJava@1
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
        jdkVersionOption: '1.17'

    - script: |
        cd GestorTareas/GestorTareasBackend/gestortareasbackend/gestortareasbackend
        mvn verify
      displayName: 'Run tests with Maven (verify phase)'

- job: Deploy
  dependsOn: Test
  steps:
    - script: echo "Deployment in progress..."
      displayName: 'Print deployment message'
